## name: GitHub Light High Contrast

foreground               #010409
background                #ffffff
selection_foreground      #010409
selection_background      #cddbf0

cursor                    #0349b4
cursor_text_color         #ffffff

url_color                 #0349b4

active_tab_foreground     #010409
active_tab_background     #ffffff
inactive_tab_foreground   #66707b
inactive_tab_background   #e7ecf0

active_border_color       #0349b4
inactive_border_color     #66707b

# black
color0   #010409
color8   #4b535d

# red
color1   #a0111f
color9   #d1242f

# green
color2   #055d20
color10  #055d20

# yellow
color3   #744500
color11  #744500

# blue
color4   #0349b4
color12  #0349b4

# magenta
color5   #512598
color13  #512598

# cyan
color6   #1b7c83
color14  #1b7c83

# white
color7   #66707b
color15  #66707b
