[metadata]
name = "Kitty Config"
supported_distros = ["manjaro", "ubuntu", "mac"]

[[symlinks]]
src = "~/dotfiles/src/terminal/kitty"
dst = "~/.config/kitty"

[[symlinks]]
src = "~/dotfiles/src/terminal/kitty/kitty-load.sh"
dst = "~/.local/bin/kitty-load"

[[deps]]
id = "kitty"
check = "command -v kitty"
[deps.install_method]
ubuntu = "curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin && ln -sf ~/.local/kitty.app/bin/kitty ~/.local/kitty.app/bin/kitten ~/.local/bin/ && sudo apt-get install -y kitty-terminfo"
manjaro = "sudo pacman -S kitty"
mac = "brew install kitty"
