pager:
  diff: delta

theme:
  colors:
    text:
      primary: "#e0def4"
      secondary: "#9ccfd8"
      inverted: "#e0def4"
      faint: "#908caa"
      warning: "#eb6f92"
      success: "#3e8fb0"
    background:
      selected: "#56526e"
    border:
      primary: "#c4a7e7"
      secondary: "#3e8fb0"
      faint: "#908caa"

defaults:
  issuesLimit: 20
  notificationsLimit: 20
  prApproveComment: ""
  preview:
    open: true
    width: 0.50
    height: 0.60
    position: auto
  prsLimit: 20
  refetchIntervalMinutes: 15
  view: prs

prSections:
  - title: "All PRs"
    filters: "is:open"
  - title: "My PRs"
    filters: "is:open author:@me"
  - title: "TypeScript"
    filters: "is:open label:typescript"
  - title: "Python"
    filters: "is:open label:python"
  - title: "Closed PRs"
    filters: "is:closed"
