[metadata]
name = "Shell (fish) config"
supported_distros = ["manjaro", "mac", "ubuntu"]

[[symlinks]]
src = "~/dotfiles/src/terminal/shell/fish"
dst = "~/.config/fish"

[[deps]]
id = "default_shell"
check = "echo $SHELL | grep -q fish"
[deps.install_method]
ubuntu = "chsh -s $(which fish)"
manjaro = "chsh -s $(which fish)"
mac = "chsh -s $(which fish)"
