local palette = require("theme_palette")

return {
  "projekt0n/github-nvim-theme",
  name = "github-theme",
  priority = 1000,
  opts = {
    groups = {
      github_light_high_contrast = {
        ["@lsp.type.variable"] = { fg = palette.fg },

        ["@variable"] = { fg = palette.fg },
        ["@variable.builtin"] = { fg = palette.purple },
        ["@variable.member"] = { fg = palette.purple },
        ["@variable.parameter"] = { fg = palette.orange },
        ["@variable.parameter.builtin"] = { fg = palette.orange },
        ["@property"] = { fg = palette.purple },
        ["@constant"] = { fg = palette.yellow },
        ["@constant.builtin"] = { fg = palette.yellow },

        ["@module"] = { fg = palette.accent },
        ["@module.builtin"] = { fg = palette.accent },
        ["@namespace"] = { fg = palette.accent },
        ["@type"] = { fg = palette.accent },
        ["@type.builtin"] = { fg = palette.accent },
        ["@type.qualifier"] = { fg = palette.purple },
        ["@constructor"] = { fg = palette.accent },

        ["@function"] = { fg = palette.green },
        ["@function.builtin"] = { fg = palette.green },
        ["@function.call"] = { fg = palette.green },
        ["@function.macro"] = { fg = palette.green },
        ["@function.method"] = { fg = palette.green },
        ["@function.method.call"] = { fg = palette.green },

        ["@keyword"] = { fg = palette.purple },
        ["@keyword.conditional"] = { fg = palette.purple },
        ["@keyword.debug"] = { fg = palette.purple },
        ["@keyword.directive"] = { fg = palette.purple },
        ["@keyword.exception"] = { fg = palette.red },
        ["@keyword.function"] = { fg = palette.purple },
        ["@keyword.import"] = { fg = palette.purple },
        ["@keyword.operator"] = { fg = palette.orange },
        ["@keyword.repeat"] = { fg = palette.purple },
        ["@keyword.return"] = { fg = palette.purple },
        ["@keyword.storage"] = { fg = palette.purple },
        ["@operator"] = { fg = palette.orange },

        ["@string"] = { fg = palette.cyan },
        ["@string.documentation"] = { fg = palette.cyan },
        ["@string.escape"] = { fg = palette.orange },
        ["@string.regexp"] = { fg = palette.orange },
        ["@string.special"] = { fg = palette.cyan },
        ["@string.special.path"] = { fg = palette.cyan },
        ["@string.special.url"] = { fg = palette.accent },
        ["@character"] = { fg = palette.cyan },
        ["@character.special"] = { fg = palette.orange },
        ["@number"] = { fg = palette.red },
        ["@number.float"] = { fg = palette.red },
        ["@boolean"] = { fg = palette.orange },

        ["@comment"] = { fg = palette.fg_subtle },
        ["@comment.documentation"] = { fg = palette.fg_muted },

        ["@tag"] = { fg = palette.red },
        ["@tag.attribute"] = { fg = palette.purple },
        ["@tag.delimiter"] = { fg = palette.fg_subtle },
        ["@attribute"] = { fg = palette.purple },
        ["@label"] = { fg = palette.yellow },
        ["@include"] = { fg = palette.purple },
        ["@preproc"] = { fg = palette.purple },
        ["@punctuation.bracket"] = { fg = palette.fg_subtle },
        ["@punctuation.delimiter"] = { fg = palette.fg_subtle },
        ["@punctuation.special"] = { fg = palette.orange },

        ["@property.yaml"] = { fg = palette.purple },
        ["@property.json"] = { fg = palette.purple },
        ["@property.toml"] = { fg = palette.purple },
        ["@string.yaml"] = { fg = palette.cyan },
        ["@string.json"] = { fg = palette.cyan },
        ["@string.toml"] = { fg = palette.cyan },
        ["@boolean.yaml"] = { fg = palette.orange },
        ["@boolean.json"] = { fg = palette.orange },
        ["@boolean.toml"] = { fg = palette.orange },
        ["@number.yaml"] = { fg = palette.red },
        ["@number.json"] = { fg = palette.red },
        ["@number.toml"] = { fg = palette.red },
        ["@comment.yaml"] = { fg = palette.fg_subtle },
        ["@comment.json"] = { fg = palette.fg_subtle },
        ["@comment.toml"] = { fg = palette.fg_subtle },
        LineNr = { fg = palette.purple },
        NonText = { fg = palette.fg_subtle },
        FloatBorder = { fg = palette.purple },
        FloatTitle = { fg = palette.yellow },
      },
    },
  },
}
