local palette = require("theme_palette")

return {
  "ellisonleao/gruvbox.nvim",
  name = "gruvbox",
  priority = 1000,
  opts = {
    contrast = "hard",
    palette_overrides = {
      dark1 = palette.fg,
      dark4 = palette.fg_subtle,
      gray = palette.fg_subtle,
      faded_orange = palette.orange,
      faded_yellow = palette.yellow,
      faded_green = palette.green,
      faded_aqua = palette.cyan,
    },
    overrides = {
      SignColumn = { bg = palette.bg },
      FoldColumn = { bg = palette.bg },
      GruvboxRedSign = { fg = palette.red, bg = palette.bg },
      GruvboxGreenSign = { fg = palette.green, bg = palette.bg },
      GruvboxYellowSign = { fg = palette.yellow, bg = palette.bg },
      GruvboxBlueSign = { fg = palette.accent, bg = palette.bg },
      GruvboxPurpleSign = { fg = palette.purple, bg = palette.bg },
      GruvboxAquaSign = { fg = palette.cyan, bg = palette.bg },
      GruvboxOrangeSign = { fg = palette.orange, bg = palette.bg },
      RenderMarkdownSign = { bg = palette.bg },
      RenderMarkdownH1Bg = { fg = palette.fg, bg = palette.bg },
      RenderMarkdownH2Bg = { bg = palette.bg },
      RenderMarkdownH3Bg = { bg = palette.bg },
      RenderMarkdownH4Bg = { bg = palette.bg },
      RenderMarkdownH5Bg = { bg = palette.bg },
      RenderMarkdownH6Bg = { bg = palette.bg },
      RenderMarkdownCode = { bg = palette.bg },
      RenderMarkdownCodeInline = { fg = palette.green, bg = palette.bg },
      ["@markup.raw.markdown_inline"] = { fg = palette.green, bg = palette.bg },
      Pmenu = { fg = palette.fg, bg = palette.bg },
      PmenuSbar = { bg = palette.bg },
      PmenuSel = { fg = palette.bg, bg = palette.accent, bold = true },
      PmenuKindSel = { fg = palette.bg, bg = palette.accent, bold = true },
      PmenuExtraSel = { fg = palette.bg, bg = palette.accent },
      BlinkCmpMenu = { fg = palette.fg, bg = palette.bg },
      BlinkCmpMenuBorder = { fg = palette.purple, bg = palette.bg },
      BlinkCmpDoc = { fg = palette.fg, bg = palette.bg },
      BlinkCmpDocBorder = { fg = palette.purple, bg = palette.bg },
      BlinkCmpDocSeparator = { fg = palette.fg_subtle, bg = palette.bg },
      BlinkCmpSignatureHelp = { fg = palette.fg, bg = palette.bg },
      BlinkCmpSignatureHelpBorder = { fg = palette.purple, bg = palette.bg },
      WhichKeyNormal = { fg = palette.fg, bg = palette.bg },
      WhichKeyBorder = { fg = palette.purple, bg = palette.bg },
      WhichKeyTitle = { fg = palette.yellow, bg = palette.bg },
      BlinkCmpGhostText = { fg = palette.fg_subtle },
      WinSeparator = { fg = palette.fg_subtle },
      VertSplit = { fg = palette.fg_subtle },
      SnacksPickerPathIgnored = { fg = palette.fg_subtle },
      CursorLine = { bg = "#f2e5bc" },
      CursorLineNr = { fg = palette.yellow, bg = "#f2e5bc" },
      MiniFilesNormal = { fg = palette.fg, bg = palette.bg },
      MiniFilesCursorLine = { bg = palette.bg_alt },
      NormalFloat = { fg = palette.fg, bg = palette.bg },
      DooingText = { link = "NormalFloat" },
      SnacksNotifierInfo = { link = "NormalFloat" },
      SnacksNotifierWarn = { link = "NormalFloat" },
      SnacksNotifierError = { link = "NormalFloat" },
      SnacksNotifierDebug = { link = "NormalFloat" },
      SnacksNotifierTrace = { link = "NormalFloat" },
      SnacksNotifierIconInfo = { link = "DiagnosticInfo" },
      SnacksNotifierIconWarn = { link = "DiagnosticWarn" },
      SnacksNotifierIconError = { link = "DiagnosticError" },

      ["@lsp.type.variable"] = { fg = palette.fg },

      ["@variable"] = { fg = palette.fg },
      ["@variable.builtin"] = { fg = palette.purple },
      ["@variable.member"] = { fg = palette.purple },
      ["@variable.parameter"] = { fg = palette.orange },
      ["@variable.parameter.builtin"] = { fg = palette.orange },
      ["@property"] = { fg = palette.purple },
      ["@constant"] = { fg = palette.yellow },
      ["@constant.builtin"] = { fg = palette.yellow },

      ["@module"] = { fg = palette.accent },
      ["@module.builtin"] = { fg = palette.accent },
      ["@namespace"] = { fg = palette.accent },
      ["@type"] = { fg = palette.accent },
      ["@type.builtin"] = { fg = palette.accent },
      ["@type.qualifier"] = { fg = palette.purple },
      ["@constructor"] = { fg = palette.accent },

      ["@function"] = { fg = palette.green },
      ["@function.builtin"] = { fg = palette.green },
      ["@function.call"] = { fg = palette.green },
      ["@function.macro"] = { fg = palette.green },
      ["@function.method"] = { fg = palette.green },
      ["@function.method.call"] = { fg = palette.green },

      ["@keyword"] = { fg = palette.purple },
      ["@keyword.conditional"] = { fg = palette.purple },
      ["@keyword.debug"] = { fg = palette.purple },
      ["@keyword.directive"] = { fg = palette.purple },
      ["@keyword.exception"] = { fg = palette.red },
      ["@keyword.function"] = { fg = palette.purple },
      ["@keyword.import"] = { fg = palette.purple },
      ["@keyword.operator"] = { fg = palette.orange },
      ["@keyword.repeat"] = { fg = palette.purple },
      ["@keyword.return"] = { fg = palette.purple },
      ["@keyword.storage"] = { fg = palette.purple },
      ["@operator"] = { fg = palette.orange },

      ["@string"] = { fg = palette.cyan },
      ["@string.documentation"] = { fg = palette.cyan },
      ["@string.escape"] = { fg = palette.orange },
      ["@string.regexp"] = { fg = palette.orange },
      ["@string.special"] = { fg = palette.cyan },
      ["@string.special.path"] = { fg = palette.cyan },
      ["@string.special.url"] = { fg = palette.accent },
      ["@character"] = { fg = palette.cyan },
      ["@character.special"] = { fg = palette.orange },
      ["@number"] = { fg = palette.red },
      ["@number.float"] = { fg = palette.red },
      ["@boolean"] = { fg = palette.orange },

      ["@comment"] = { fg = palette.fg_subtle },
      ["@comment.documentation"] = { fg = palette.fg_muted },

      ["@tag"] = { fg = palette.red },
      ["@tag.attribute"] = { fg = palette.purple },
      ["@tag.delimiter"] = { fg = palette.fg_subtle },
      ["@attribute"] = { fg = palette.purple },
      ["@label"] = { fg = palette.yellow },
      ["@include"] = { fg = palette.purple },
      ["@preproc"] = { fg = palette.purple },
      ["@punctuation.bracket"] = { fg = palette.fg_subtle },
      ["@punctuation.delimiter"] = { fg = palette.fg_subtle },
      ["@punctuation.special"] = { fg = palette.orange },

      ["@property.yaml"] = { fg = palette.purple },
      ["@property.json"] = { fg = palette.purple },
      ["@property.toml"] = { fg = palette.purple },
      ["@string.yaml"] = { fg = palette.cyan },
      ["@string.json"] = { fg = palette.cyan },
      ["@string.toml"] = { fg = palette.cyan },
      ["@boolean.yaml"] = { fg = palette.orange },
      ["@boolean.json"] = { fg = palette.orange },
      ["@boolean.toml"] = { fg = palette.orange },
      ["@number.yaml"] = { fg = palette.red },
      ["@number.json"] = { fg = palette.red },
      ["@number.toml"] = { fg = palette.red },
      ["@comment.yaml"] = { fg = palette.fg_subtle },
      ["@comment.json"] = { fg = palette.fg_subtle },
      ["@comment.toml"] = { fg = palette.fg_subtle },
      LineNr = { fg = palette.purple },
      NonText = { fg = palette.fg_subtle },
      FloatBorder = { fg = palette.purple, bg = palette.bg },
      FloatTitle = { fg = palette.yellow, bg = palette.bg },
      FloatFooter = { fg = palette.yellow, bg = palette.bg },
      NoicePopup = { link = "NormalFloat" },
      NoicePopupBorder = { link = "FloatBorder" },
      NoiceMini = { link = "NormalFloat" },
    },
  },
}
