[metadata]
name = "Lazygit Config"
supported_distros = ["manjaro", "ubuntu", "mac"]

[[symlinks]]
src = "~/dotfiles/lazygit"
dst = "~/.config/lazygit"

[[deps]]
id = "lazygit"
[deps.install_method]
ubuntu = "sudo apt install lazygit"
manjaro = "sudo pacman -S lazygit"
mac = "brew install lazygit"

[[deps]]
id = "lazygit"
[deps.install_method]
ubuntu = "sudo apt install lazygit"
manjaro = "sudo pacman -S lazygit"
mac = "brew install lazygit"
