# BEGIN_KITTY_THEME
include current-theme.conf
# END_KITTY_THEME

# Fonts
font_family         JetBrainsMono Nerd Font Mono Regular
bold_font           JetBrainsMono Nerd Font Mono Extrabold
italic_font         JetBrainsMono Nerd Font Mono Italic
bold_italic_font    JetBrainsMono Nerd Font Mono ExtraBold Italic
font_size           12
symbol_map U+E000-U+E00A,U+EA60-U+EBEB,U+E0A0-U+E0C8,U+E0CA,U+E0CC-U+E0D7,U+E200-U+E2A9,U+E300-U+E3E3,U+E5FA-U+E6B5,U+E700-U+E7C5,U+ED00-U+EFC1,U+F000-U+F2FF,U+F300-U+F372,U+F400-U+F533,U+F0001-U+F1AF0 JetBrainsMono Nerd Font Mono

# Tab 
tab_bar_min_tabs            1
tab_bar_edge                top
tab_bar_style               powerline
tab_powerline_style         slanted
tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}

# little bit of padding so `ls` doesn't put everything so close
window_padding_width 3 

# Keys
map f12>shift+h previous_tab
map f12>shift+l next_tab
map f12>b select_tab
map f12>c new_tab_with_cwd
map f12>t new_tab
map f12>q close_window
map f12>1 goto_tab 1
map f12>2 goto_tab 2
map f12>3 goto_tab 3
map f12>4 goto_tab 4
map f12>5 goto_tab 5
map f12>6 goto_tab 6
map f12>7 goto_tab 7
map f12>8 goto_tab 8
map f12>9 goto_tab 9
map f12>0 goto_tab 10
map f12>m detach_window ask
map f12>| launch --location=vsplit --cwd=current
map f12>\ launch --location=hsplit --cwd=current
map f12>l neighboring_window right
map f12>h neighboring_window left
map f12>j neighboring_window bottom
map f12>k neighboring_window top


background_opacity .9
background_blur 1

enabled_layouts splits,horizontal

