[metadata]
name = "Starship Config"
supported_distros = ["manjaro", "ubuntu", "mac"]

[[symlinks]]
src = "~/dotfiles/terminal/starship"
dst = "~/.config/starship"

[[deps]]
id = "starship"
[deps.install_method]
ubuntu = "sh ~/dotfiles/terminal/starship/ubuntu_install.sh"
manjaro = "sudo pacman -S starship"
mac = "brew install starship"
