"$schema" = 'https://starship.rs/config-schema.json'

scan_timeout = 100

format = """
$username\
$directory\
$git_branch\
$git_metrics\
$git_status\
$fill\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
$conda\
$python\
$time\
$line_break\
$character"""

palette = "rose-pine-moon"

[palettes.rose-pine-moon]
overlay = '#393552'
love = '#eb6f92'
gold = '#f6c177'
rose = '#ea9a97'
pine = '#3e8fb0'
foam = '#9ccfd8'
iris = '#c4a7e7'

[username]
disabled = false
format = "[](fg:overlay)[ 󰧱 $user ](bg:overlay fg:iris)[](fg:overlay) "
show_always = true
style_root = "bg:overlay fg:iris"
style_user = "bg:overlay fg:iris"

[directory]
format = "[](fg:overlay)[ 󰉋 $path ](bg:overlay fg:gold)[](fg:overlay) "
style = "bg:overlay fg:pine"
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = true
read_only = "󰌾"
home_symbol = "~"

[directory.substitutions]
Documents = "󰈙"
Downloads = " "
Music = " "
Pictures = " "

[fill]
style = "fg:overlay"
symbol = " "

[git_branch]
format = "[](fg:overlay)[  $branch ](bg:overlay fg:foam)"
style = "bg:overlay fg:foam"
symbol = ""

[git_status]
disabled = false
format = '[](fg:overlay) '
up_to_date = ''
untracked = ''
stashed = ''
modified = ''
renamed = ''
deleted = ''
staged = ''
ahead = ''
behind = ''
diverged = ''

[git_metrics]
disabled = false
added_style = "bg:overlay fg:foam"
deleted_style = "bg:overlay fg:love"
format = "([+$added ]($added_style)[-$deleted ]($deleted_style))"

[time]
disabled = false
format = " [](fg:overlay)[ $time 󰴈 ](bg:overlay fg:rose)[](fg:overlay)"
style = "bg:overlay fg:rose"
time_format = "%I:%M%P"
use_12hr = true

[character]
disabled = false
success_symbol = '[󱞪](bold fg:iris)'
error_symbol = '[󱞪](bold fg:love)'

[line_break]
disabled = false

# -- Languages --

[c]
disabled = false
symbol = " "
style = "bg:overlay fg:pine"
format = " [](fg:overlay)[ $symbol$version ](bg:overlay fg:pine)[](fg:overlay)"

[elixir]
disabled = false
symbol = " "
style = "bg:overlay fg:pine"
format = " [](fg:overlay)[ $symbol$version ](bg:overlay fg:pine)[](fg:overlay)"

[elm]
disabled = false
symbol = " "
style = "bg:overlay fg:pine"
format = " [](fg:overlay)[ $symbol$version ](bg:overlay fg:pine)[](fg:overlay)"

[golang]
disabled = false
symbol = " "
style = "bg:overlay fg:pine"
format = " [](fg:overlay)[ $symbol$version ](bg:overlay fg:pine)[](fg:overlay)"

[haskell]
disabled = false
symbol = " "
style = "bg:overlay fg:pine"
format = " [](fg:overlay)[ $symbol$version ](bg:overlay fg:pine)[](fg:overlay)"

[java]
disabled = false
symbol = " "
style = "bg:overlay fg:pine"
format = " [](fg:overlay)[ $symbol$version ](bg:overlay fg:pine)[](fg:overlay)"

[julia]
disabled = false
symbol = " "
style = "bg:overlay fg:pine"
format = " [](fg:overlay)[ $symbol$version ](bg:overlay fg:pine)[](fg:overlay)"

[nodejs]
disabled = false
symbol = "󰎙 "
style = "bg:overlay fg:pine"
format = " [](fg:overlay)[ $symbol$version ](bg:overlay fg:pine)[](fg:overlay)"

[nim]
disabled = false
symbol = "󰆥 "
style = "bg:overlay fg:pine"
format = " [](fg:overlay)[ $symbol$version ](bg:overlay fg:pine)[](fg:overlay)"

[rust]
disabled = false
symbol = " "
style = "bg:overlay fg:pine"
format = " [](fg:overlay)[ $symbol$version ](bg:overlay fg:pine)[](fg:overlay)"

[scala]
disabled = false
symbol = " "
style = "bg:overlay fg:pine"
format = " [](fg:overlay)[ $symbol$version ](bg:overlay fg:pine)[](fg:overlay)"

[python]
disabled = false
symbol = ' '
style = "bg:overlay fg:pine"
format = " [](fg:overlay)[ $symbol$version( $virtualenv) ](bg:overlay fg:pine)[](fg:overlay)"

[conda]
disabled = false
symbol = '🅒 '
style = "bg:overlay fg:pine"
format = " [](fg:overlay)[ $symbol$environment ](bg:overlay fg:pine)[](fg:overlay)"
