[metadata]
name = "Shell (fish) config"
supported_distros = ["manjaro", "mac", "ubuntu"]

[[symlinks]]
src = "~/dotfiles/terminal/shell/fish"
dst = "~/.config/fish"

[[deps]]
id = "default_shell"
[deps.install_method]
ubuntu = "chsh -s $(which fish)"
manjaro = "chsh -s $(which fish)"
mac = "chsh -s $(which fish)"
