[metadata]
name = "Hyprland Configs"
supported_distros = ["manjaro"]

[[symlinks]]
src = "~/dotfiles/src/linux/manjaro/hyprland/hypr"
dst = "~/.config/hypr"

[[symlinks]]
src = "~/dotfiles/src/linux/manjaro/hyprland/hyprpanel"
dst = "~/.config/hyprpanel"

[[deps]]
id = "hyprland"
[deps.install_method]
manjaro = "sudo pacman -S hyprland"


[[deps]]
id = "hyprcursor"
[deps.install_method]
manjaro = "sudo pacman -S hyprcursor"

[[deps]]
id = "hyprpaper"
[deps.install_method]
manjaro = "sudo pacman -S hyprpaper"

[[deps]]
id = "xdg-desktop-portal-hyprland"
[deps.install_method]
manjaro = "sudo pacman -S xdg-desktop-portal-hyprland"

[[deps]]
id = "xdg-desktop-portal-gtk"
[deps.install_method]
manjaro = "sudo pacman -S xdg-desktop-portal-gtk"

[[deps]]
id = "hypridle"
[deps.install_method]
manjaro = "sudo pacman -S hypridle"

[[deps]]
id = "hyprlock"
[deps.install_method]
manjaro = "sudo pacman -S hyprlock"

[[deps]]
id = "hyprpanel"
[deps.install_method]
manjaro = "sudo yay -S ags-hyprpanel-git"

[[deps]]
id = "cursor_theme"
[deps.install_method]
manjaro = "sudo yay -S bibata-cursor-theme"

[[deps]]
id = "hyprshot"
[deps.install_method]
manjaro = "sudo yay -S hyprshot"

[[deps]]
id = "hyprpolkitagent"
[deps.install_method]
manjaro = "sudo pacman -S hyprpolkitagent"
