[metadata]
name = "Dotfiles Config"
supported_distros = ["mac", "manjaro", "ubuntu"]


[[deps]]
id = "node_version_manager"
[deps.install_method]
manjaro = "curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.4/install.sh | bash"
ubuntu = "curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.4/install.sh | bash"
mac = "curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.4/install.sh | bash"

[[deps]]
id = "node_js"
[deps.install_method]
manjaro = "nvm install --lts"
ubuntu = "nvm install --lts"
mac = "nvm install --lts"

[[deps]]
id = "vivaldi"
[deps.install_method]
manjaro = "sudo pacman -S vivaldi"
ubuntu = "echo 'install vivaldi manually or just use chrome'"
mac = "brew install --cask vivaldi"
