set -g status-style "bg=#e7ecf0,fg=#010409"
set -g pane-border-style "fg=#4b535d"
set -g pane-active-border-style "fg=#0349b4"
set -g status-left-length 60
set -g status-right-length 60

# -- Session name --
set -g status-left "#[fg=#512598,bold]  #S #[fg=#4b535d,nobold] / "

# -- Window list --
set -g window-status-separator " / "
set -g window-status-format "#[fg=#4b535d] #I. 󰉋 #{b:pane_current_path}#[fg=#702c00]#{?#{!=:#(cd #{pane_current_path} 2>/dev/null && git branch --show-current 2>/dev/null),}, ( #(cd #{pane_current_path} 2>/dev/null && git branch --show-current 2>/dev/null)),}"
set -g window-status-current-format "#[fg=#0349b4,bold] #I. 󰉋 #{b:pane_current_path}#[fg=#702c00]#{?#{!=:#(cd #{pane_current_path} 2>/dev/null && git branch --show-current 2>/dev/null),}, ( #(cd #{pane_current_path} 2>/dev/null && git branch --show-current 2>/dev/null)),}#[fg=#0349b4,nobold]"

