set -g status-style "bg=#363a4f,fg=#cad3f5"
set -g message-style "bg=#363a4f,fg=#cad3f5"
set -g message-command-style "bg=#363a4f,fg=#cad3f5"
set -g mode-style "bg=#494d64,fg=#cad3f5"
set -g status-right-style "fg=#939ab7"
set -g pane-border-style "fg=#b8c0e0"
set -g pane-active-border-style "fg=#8aadf4"
set -g status-left-length 60
set -g status-right-length 60

# -- Session name --
set -g status-left "#[fg=#c6a0f6,bold]  #S #[fg=#b8c0e0,nobold] / "

# -- Window list --
set -g window-status-separator " / "
set -g window-status-format "#[fg=#b8c0e0] #I. 󰉋 #{b:pane_current_path}#[fg=#f5a97f]#{?#{!=:#(cd #{pane_current_path} 2>/dev/null && git branch --show-current 2>/dev/null),}, ( #(cd #{pane_current_path} 2>/dev/null && git branch --show-current 2>/dev/null)),}"
set -g window-status-current-format "#[fg=#8aadf4,bold] #I. 󰉋 #{b:pane_current_path}#[fg=#f5a97f]#{?#{!=:#(cd #{pane_current_path} 2>/dev/null && git branch --show-current 2>/dev/null),}, ( #(cd #{pane_current_path} 2>/dev/null && git branch --show-current 2>/dev/null)),}#[fg=#8aadf4,nobold]"
