[metadata]
name = "Ubuntu Config"
supported_distros = ["ubuntu"]

[[deps]]
id = "dunst"
[deps.install_method]
ubuntu = "sudo apt install dunst"

[[deps]]
id = "feh"
[deps.install_method]
ubuntu = "sudo apt install feh"

[[deps]]
id = "picom"
[deps.install_method]
ubuntu = "sudo apt install picom"

[[symlinks]]
src = "~/dotfiles/src/linux/ubuntu/picom"
dst = "~/.config/picom"
