general {
    lock_cmd = pidof hyprlock || hyprlock       # avoid starting multiple hyprlock instances.
    before_sleep_cmd = hyprlock
}

# hyprlock after 5 mins
listener {
    timeout    = 300      
    on-timeout = pidof hyprlock || hyprlock
}

# poweroff after 30 mins
listener {
    timeout    = 1800     # 30 minutes
    on-timeout = systemctl poweroff
}
